openapi: 3.0.3
info:
  title: PowerManage API
  version: 1.0.0
  description: |
    # PowerManage API

    ## Introduction
    Visonic/Tyco have their own REST API that is used for the following apps:

    - Visonic-Go
    - AlarmInstall
    - ConnectAlarm

    The API points to Visonic/Tyco's PowerManage servers which then passes the request to the alarm panel.

    ## Details
    General information about available interfaces is organized into the following sections:
    - REST: Endpoints used by normal end users and apps.
    - Installer: Endpoints and notes relevant to installers.

    ## REST
    The REST interface is used by normal users and consumer applications.
    - Base endpoint: `https://visonic.tycomonitor.com/rest_api/{rest_version}`

    ## Installer
    The Installer interface is used by professional installers and installer apps.
    - Base endpoint: `https://visonic.tycomonitor.com/rest_api/installer/{installer_version}`
servers: []

tags:
  - name: REST
    description: |
      Endpoints used by normal end users and apps.
      Base: https://visonic.tycomonitor.com/rest_api/{rest_version}
  - name: Installer
    description: |
      Endpoints for installer workflows.
      Base: https://visonic.tycomonitor.com/rest_api/installer/{installer_version}

paths:
  /apptype:
    $ref: './api/apptype.yaml'
